export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const UPDATE_API_TOKEN = 'UPDATE_API_TOKEN';