export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const UPDATE_API_TOKEN = 'UPDATE_API_TOKEN';

export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const UPDATE_SELECTED_REPO = 'UPDATE_SELECTED_REPO';

export const UPDATE_SORT_ORDER = 'UPDATE_SORT_ORDER';